In [15]:
# Create 2 new departments in the department table:
'''
[
    ['CSALE', 'Corporate External Sales'],
    ['ISALE', 'Corporate Inside Sales'],
]
'''

# Create 3 new employees in employees table
'''
[
    [100, 'Kellogg', 'Roger', 'Divorced', 'CSALE', 001]
    [101, 'Wilder', 'Laura', 'Married', 'CSALE', 100]
    [102, 'Pratt', 'Thomas', 'Married', 'CSALE', 100]
]
'''

# Create a new table called 'sales'
# Insert data into sales table:
'''
[
    [100,'INSIDE','2020/11/20',15000],
    [100,'INSIDE','2020/12/05',35000],
    [100,'INSIDE','2020/10/02',50000],
    [101,'INSIDE','2020/10/02','REAL'],
    [100,'INSIDE','2020/10/02','REAL'],
    [101,'INSIDE','2020/11/10',45000],
    [101,'INSIDE','2020/10/16',22000],
    [101,'INSIDE','2020/12/08',26000],
]
'''

In [21]:
import sqlite3

connection = sqlite3.connect('employee_data.db')
cursor = connection.cursor()



#----------------------------------------------------------------------------------------------------------------
# New department Data
new_departments = [
    ['CSALE', 'Corporate External Sales'],
    ['ISALE', 'Corporate Inside Sales'],
]
# Inserting new department data
cursor.executemany('insert into departments values (?,?)',(new_departments))



#----------------------------------------------------------------------------------------------------------------
# New employees data
new_employees = [
    [100, 'Kellogg', 'Roger', 'Divorced', 'CSALE', '001'],
    [101, 'Wilder', 'Laura', 'Married', 'CSALE', '100'],
    [102, 'Pratt', 'Thomas', 'Married', 'CSALE', '100']
]
# Inserting new employees to employees table
cursor.executemany('insert into employees (employee_id,last_name,first_name,marital_status,dept_id,manager_id) values (?,?,?,?,?,?)',new_employees)



#----------------------------------------------------------------------------------------------------------------
# Create Sales Table
cursor.execute('create table if not exists sales (employee_id int, sale_type text, sale_data text, sale_amount real)')

# New Sales Data
new_sales = [
    [100,'INSIDE','2020/11/20',15000],
    [100,'INSIDE','2020/12/05',35000],
    [100,'INSIDE','2020/10/02',50000],
    [101,'INSIDE','2020/10/02','REAL'],
    [100,'INSIDE','2020/10/02','REAL'],
    [101,'INSIDE','2020/11/10',45000],
    [101,'INSIDE','2020/10/16',22000],
    [101,'INSIDE','2020/12/08',26000],
]
# Inserting new sales into sales table
cursor.executemany('insert into sales values(?,?,?,?)',(new_sales))



connection.commit()
connection.close()